@file:JsModule("@zowe/zos-tso-for-zowe-sdk")

package zowe.sdk.zos.tso

import js.promise.Promise
import zowe.imperative.rest.session.AbstractSession
import zowe.sdk.zos.tso.doc.IPingResponse

external class PingTso {
  companion object {
    /**
     * Issue a TSO Ping command, returns [IPingResponse] result, see [IPingResponse]
     * @param session representing connection to this api
     * @param servletKey servletkey for address space to ping, generated by start command
     */
    fun ping(
      session: AbstractSession,
      servletKey: String,
    ): Promise<IPingResponse>

    /**
     * Get resource path for ping command
     * @param servletKey servelet key from start API method
     * @return resource path
     */
    fun getResource(servletKey: String): String
  }
}
